#!/usr/bin/env bash
# Unified camflow task entry point.
#
# If scripts/tasks.cfg is missing, this script creates it. In interactive terminals it
# asks for all values first; in non-interactive runs it writes defaults.

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_DIR=$(cd -- "${SCRIPT_DIR}/.." && pwd)
MAKE_CFG_PATH="${SCRIPT_DIR}/tasks.cfg"

DEFAULT_BUILD_TYPE=Debug
DEFAULT_TARGET=imx8mp-var-dart
DEFAULT_TARGET_DIR=/usr/bin
DEFAULT_PORT=8000
DEFAULT_USER=root
DEFAULT_OPENCV_VERSION=4.12.0
DEFAULT_LOCAL_DEVICE=
DEFAULT_LOCAL_SUBDEVICES=
DEFAULT_REMOTE_DEVICE=
DEFAULT_REMOTE_SUBDEVICES=
DEFAULT_TAIL_LOG=1
DEFAULT_VERBOSE_LEVEL=3
DEFAULT_LOG_PATH=/tmp/camflow-local-ui.log
DEFAULT_UI_OUT_DIR="${PROJECT_DIR}/web/dist"
DEFAULT_UI_WORK_DIR="${PROJECT_DIR}/web"
DEFAULT_UI_DEV_PORT=8081
DEFAULT_UI_API_PORT=8000
DEFAULT_ARM64_BUILD_DIR=build-runtime-arm64
DEFAULT_ARM64_IMAGE=camflow-arm64
DEFAULT_ARM64_REBUILD_IMAGE=0

print_help() {
    cat <<EOF
Usage: ./scripts/tasks.sh <command> [command ...] [platform ...] [product ...] [options]

Commands:
  build          Build the selected products.
  deploy         Deploy the runtime binary to the ARM64 target.
  run            Run the selected runtime(s).
    deps           Install host dependencies and project-local OpenCV package.
    format         Format C/C++ sources using clang-format.
    docs           Generate Doxygen API documentation.
    ui-release     Rebuild web/dist-release from web/src (requires Node.js); commit the result so
                   Node-free hosts can embed the UI without npm.

Platforms:
  dev            Native Linux development build/run.
  arm64          ARM64 cross build/deploy/run.

Products:
  runtime        C++ runtime binary.
  ui             React UI bundle.

Options:
  --ip HOST      Target host/IP for ARM64 deployment and remote UI.
  --dir DIR      Target directory on the ARM64 host.
  --port PORT    UI port for local and remote runtime runs.
    --tail-log 0|1 Override runtime log tailing behavior for run commands.
    --log-path PATH
                                Override runtime log output path (use /dev/null to disable file logging).
  --user USER    SSH user for ARM64 deployment and remote UI.
  --opencv VER   OpenCV version folder name.
    --rebuild-image 0|1
                                                                Force rebuild of ARM64 Docker image before cross-build.
  --ui-out DIR   UI build output directory (used by CMake integration).
  --ui-work DIR  UI working directory (used by CMake integration).
    --ui-port PORT UI dev server port (Vite with hot reload).
    --api-port PORT
                                Runtime API port proxied by the UI dev server.
    --clang-format BIN
                                    clang-format executable for the format action.
    --clean        Clean docs output before the docs action.
    --output DIR   Docs output directory for the docs action.
    --install-deps Install documentation dependencies for the docs action.
  --help         Show this help text.

Examples:
    ./scripts/tasks.sh build
    ./scripts/tasks.sh build deploy run arm64 runtime --ip 192.168.1.10
    ./scripts/tasks.sh build ui dev
    ./scripts/tasks.sh run dev ui --ui-port 8081 --api-port 8000
    ./scripts/tasks.sh run dev runtime ui --port 8000 --ui-port 8081 --api-port 8000
    ./scripts/tasks.sh build dev ui --ui-out build-runtime/web-dist --ui-work build-runtime/web-build
    ./scripts/tasks.sh deps --opencv 4.12.0
    ./scripts/tasks.sh format --clang-format clang-format-15
    ./scripts/tasks.sh docs --clean --install-deps
    ./scripts/tasks.sh ui-release
EOF
}

has_help_flag() {
    local arg
    for arg in "$@"; do
        case "${arg}" in
            -h|--help|help)
                return 0
                ;;
        esac
    done
    return 1
}

prompt_value() {
    local label="$1"
    local default_value="$2"
    local value=""
    read -r -p "${label} [${default_value}]: " value
    printf '%s' "${value:-${default_value}}"
}

cfg_assign() {
    local name="$1"
    local value="$2"
    printf '%s=%q\n' "${name}" "${value}"
}

host_arch() {
    local arch
    arch="$(uname -m)"
    case "${arch}" in
        amd64)
            echo "x86_64"
            ;;
        aarch64)
            echo "arm64"
            ;;
        *)
            echo "${arch}"
            ;;
    esac
}

write_make_cfg() {
    {
        echo "# Local camflow script defaults."
        echo "# Generated by scripts/tasks.sh."
        echo
        cfg_assign BUILD_TYPE "${BUILD_TYPE}"
        cfg_assign TARGET "${TARGET}"
        cfg_assign TARGET_DIR "${TARGET_DIR}"
        cfg_assign PORT "${PORT}"
        cfg_assign USER "${USER}"
        cfg_assign OPENCV_VERSION "${OPENCV_VERSION}"
        cfg_assign LOCAL_DEVICE "${LOCAL_DEVICE}"
        cfg_assign LOCAL_SUBDEVICES "${LOCAL_SUBDEVICES}"
        cfg_assign REMOTE_DEVICE "${REMOTE_DEVICE}"
        cfg_assign REMOTE_SUBDEVICES "${REMOTE_SUBDEVICES}"
        cfg_assign TAIL_LOG "${TAIL_LOG}"
        cfg_assign VERBOSE_LEVEL "${VERBOSE_LEVEL}"
        cfg_assign LOG_PATH "${LOG_PATH}"
        cfg_assign UI_DEV_PORT "${UI_DEV_PORT}"
        cfg_assign UI_API_PORT "${UI_API_PORT}"
    } > "${MAKE_CFG_PATH}"
}

create_make_cfg_interactive() {
    echo "scripts/tasks.cfg not found. Enter defaults to create it."
    BUILD_TYPE=$(prompt_value "Build type" "${DEFAULT_BUILD_TYPE}")
    TARGET=$(prompt_value "ARM64 target host" "${DEFAULT_TARGET}")
    TARGET_DIR=$(prompt_value "ARM64 target directory" "${DEFAULT_TARGET_DIR}")
    PORT=$(prompt_value "UI port" "${DEFAULT_PORT}")
    USER=$(prompt_value "SSH user" "${DEFAULT_USER}")
    OPENCV_VERSION=$(prompt_value "OpenCV version" "${DEFAULT_OPENCV_VERSION}")
    LOCAL_DEVICE=$(prompt_value "Local camera device" "${DEFAULT_LOCAL_DEVICE}")
    LOCAL_SUBDEVICES=$(prompt_value "Local subdevices (comma-separated)" "${DEFAULT_LOCAL_SUBDEVICES}")
    REMOTE_DEVICE=$(prompt_value "Remote camera device" "${DEFAULT_REMOTE_DEVICE}")
    REMOTE_SUBDEVICES=$(prompt_value "Remote subdevices (comma-separated)" "${DEFAULT_REMOTE_SUBDEVICES}")
    TAIL_LOG=$(prompt_value "Tail logs by default (1/0)" "${DEFAULT_TAIL_LOG}")
    VERBOSE_LEVEL=$(prompt_value "Verbose level" "${DEFAULT_VERBOSE_LEVEL}")
    LOG_PATH=$(prompt_value "Local log path" "${DEFAULT_LOG_PATH}")
    UI_DEV_PORT=$(prompt_value "UI dev server port" "${DEFAULT_UI_DEV_PORT}")
    UI_API_PORT=$(prompt_value "UI proxy API port" "${DEFAULT_UI_API_PORT}")
    write_make_cfg
    echo "Created ${MAKE_CFG_PATH}"
}

create_make_cfg_defaults() {
    BUILD_TYPE=${DEFAULT_BUILD_TYPE}
    TARGET=${DEFAULT_TARGET}
    TARGET_DIR=${DEFAULT_TARGET_DIR}
    PORT=${DEFAULT_PORT}
    USER=${DEFAULT_USER}
    OPENCV_VERSION=${DEFAULT_OPENCV_VERSION}
    LOCAL_DEVICE=${DEFAULT_LOCAL_DEVICE}
    LOCAL_SUBDEVICES=${DEFAULT_LOCAL_SUBDEVICES}
    REMOTE_DEVICE=${DEFAULT_REMOTE_DEVICE}
    REMOTE_SUBDEVICES=${DEFAULT_REMOTE_SUBDEVICES}
    TAIL_LOG=${DEFAULT_TAIL_LOG}
    VERBOSE_LEVEL=${DEFAULT_VERBOSE_LEVEL}
    LOG_PATH=${DEFAULT_LOG_PATH}
    UI_DEV_PORT=${DEFAULT_UI_DEV_PORT}
    UI_API_PORT=${DEFAULT_UI_API_PORT}
    write_make_cfg
    echo "Created ${MAKE_CFG_PATH} from defaults"
}

ensure_make_cfg() {
    if [[ -f "${MAKE_CFG_PATH}" ]]; then
        return
    fi

    if [[ -t 0 ]]; then
        create_make_cfg_interactive
    else
        create_make_cfg_defaults
    fi
}

load_make_cfg() {
    # shellcheck disable=SC1090
    source "${MAKE_CFG_PATH}"
}

has_command() {
    local wanted="$1"
    local cmd
    for cmd in "${commands[@]}"; do
        if [[ "${cmd}" == "${wanted}" ]]; then
            return 0
        fi
    done
    return 1
}

install_ui_dependencies() {
    local ui_dir="$1"
    local lock_file="${ui_dir}/package-lock.json"
    local node_modules_dir="${ui_dir}/node_modules"
    local hash_file="${node_modules_dir}/.camflow-lock-hash"
    local env_file="${node_modules_dir}/.camflow-node-env"
    local current_hash=""
    local stored_hash=""
    local current_env=""
    local stored_env=""

    if ! command -v npm >/dev/null 2>&1; then
        echo "npm is required but not found" >&2
        exit 1
    fi

    if [[ -f "${lock_file}" ]]; then
        if command -v sha256sum >/dev/null 2>&1; then
            current_hash="$(sha256sum "${lock_file}" | awk '{print $1}')"
        elif command -v shasum >/dev/null 2>&1; then
            current_hash="$(shasum -a 256 "${lock_file}" | awk '{print $1}')"
        fi
    fi

    current_env="$(node -p "process.platform + '-' + process.arch + '-' + process.versions.modules")"

    if [[ -f "${hash_file}" ]]; then
        stored_hash="$(cat "${hash_file}")"
    fi
    if [[ -f "${env_file}" ]]; then
        stored_env="$(cat "${env_file}")"
    fi

    if [[ -d "${node_modules_dir}" && -z "${stored_env}" ]]; then
        echo "Node module cache metadata missing; reinstalling dependencies in ${ui_dir}"
        if ! rm -rf "${node_modules_dir}" 2>/dev/null; then
            echo "Failed to remove ${node_modules_dir}" >&2
            return 75
        fi
        stored_hash=""
    fi

    if [[ -d "${node_modules_dir}" && -n "${stored_env}" && "${stored_env}" != "${current_env}" ]]; then
        echo "Node module cache environment changed (${stored_env} -> ${current_env}); reinstalling dependencies in ${ui_dir}"
        if ! rm -rf "${node_modules_dir}" 2>/dev/null; then
            echo "Failed to remove ${node_modules_dir}" >&2
            return 75
        fi
        stored_hash=""
    fi

    if [[ -d "${node_modules_dir}" && -n "${current_hash}" && "${current_hash}" == "${stored_hash}" ]]; then
        echo "Reusing React dependencies in ${ui_dir}"
        return
    fi

    echo "Installing React dependencies in ${ui_dir}"
    (
        cd "${ui_dir}"
        npm install
    )

    if [[ -n "${current_hash}" ]]; then
        mkdir -p "${node_modules_dir}"
        printf '%s\n' "${current_hash}" > "${hash_file}"
    fi
    printf '%s\n' "${current_env}" > "${env_file}"
}

sync_ui_sources_to_workdir() {
    local source_ui_dir="$1"
    local work_ui_dir="$2"

    mkdir -p "${work_ui_dir}"

    # Keep node_modules cache between runs to avoid reinstalling unchanged deps.
    find "${work_ui_dir}" -mindepth 1 -maxdepth 1 ! -name node_modules -exec rm -rf {} +

    cp "${source_ui_dir}/index.html" "${work_ui_dir}/index.html"
    cp "${source_ui_dir}/package.json" "${work_ui_dir}/package.json"
    cp "${source_ui_dir}/package-lock.json" "${work_ui_dir}/package-lock.json"
    cp "${source_ui_dir}/vite.config.js" "${work_ui_dir}/vite.config.js"
    cp -R "${source_ui_dir}/src" "${work_ui_dir}/src"
}

compute_ui_source_hash() {
    (
        cd "${PROJECT_DIR}/web"
        find index.html package.json package-lock.json vite.config.js src -type f \
            | LC_ALL=C sort | xargs sha256sum | sha256sum | awk '{print $1}'
    )
}

use_committed_ui_release() {
    local output_dir="$1"
    local release_dir="${PROJECT_DIR}/web/dist-release"
    local current_hash
    local stored_hash=""

    if [[ ! -f "${release_dir}/index.html" ]]; then
        echo "npm is required but not found, and no committed fallback exists at ${release_dir}." >&2
        echo "Run ./scripts/tasks.sh build ui-release once on a host with Node.js to create it." >&2
        exit 1
    fi

    current_hash="$(compute_ui_source_hash)"
    if [[ -f "${release_dir}/.source-hash" ]]; then
        stored_hash="$(cat "${release_dir}/.source-hash")"
    fi
    if [[ "${current_hash}" != "${stored_hash}" ]]; then
        echo "WARNING: web/dist-release is out of date with web/src (no Node.js available to rebuild it)." >&2
        echo "The embedded UI may not reflect the latest source changes." >&2
    fi

    rm -rf "${output_dir}"
    mkdir -p "$(dirname -- "${output_dir}")"
    cp -R "${release_dir}" "${output_dir}"
    echo "npm not found; used committed UI assets from ${release_dir} (Node-free build)."
}

build_web_ui() {
    local source_ui_dir="${PROJECT_DIR}/web"
    local output_dir="${1:-${UI_OUT_DIR}}"
    local work_ui_dir="${2:-${UI_WORK_DIR}}"
    local fallback_output_dir="/tmp/camflow-ui-dist"
    local fallback_work_ui_dir="/tmp/camflow-ui-work"
    local current_hash

    current_hash="$(compute_ui_source_hash)"
    if [[ -f "${output_dir}/index.html" && -f "${output_dir}/assets/app.js" && -f "${output_dir}/assets/app.css" \
          && -f "${output_dir}/.source-hash" && "$(cat "${output_dir}/.source-hash")" == "${current_hash}" ]]; then
        echo "UI assets in ${output_dir} already match web/src (unchanged); skipping rebuild."
        return
    fi

    if ! command -v npm >/dev/null 2>&1; then
        use_committed_ui_release "${output_dir}"
        return
    fi

    if [[ "${work_ui_dir}" != "${source_ui_dir}" ]]; then
        sync_ui_sources_to_workdir "${source_ui_dir}" "${work_ui_dir}"
    fi

    if ! install_ui_dependencies "${work_ui_dir}"; then
        if [[ "${work_ui_dir}" == "${source_ui_dir}" ]]; then
            echo "Warning: source UI dependencies are not writable. Falling back to ${fallback_work_ui_dir}." >&2
            echo "Hint: fix ownership of ${source_ui_dir}/node_modules to remove this warning." >&2
            work_ui_dir="${fallback_work_ui_dir}"
            sync_ui_sources_to_workdir "${source_ui_dir}" "${work_ui_dir}"
            install_ui_dependencies "${work_ui_dir}"
        else
            echo "Failed to prepare dependencies in ${work_ui_dir}" >&2
            exit 1
        fi
    fi

    if ! rm -rf "${output_dir}"; then
        if [[ "${output_dir}" == "${DEFAULT_UI_OUT_DIR}" ]]; then
            echo "Warning: could not clean ${output_dir}. Falling back to ${fallback_output_dir}." >&2
            echo "Hint: fix permissions for ${output_dir} or pass --ui-out explicitly." >&2
            output_dir="${fallback_output_dir}"
            rm -rf "${output_dir}"
        else
            echo "Failed to clean UI output directory: ${output_dir}" >&2
            echo "Hint: fix permissions or choose a different directory with --ui-out." >&2
            exit 1
        fi
    fi

    mkdir -p "$(dirname -- "${output_dir}")"
    (
        cd "${work_ui_dir}"
        CAMFLOW_WEB_OUT_DIR="${output_dir}" npm run build
    )

    if [[ ! -f "${output_dir}/index.html" ]]; then
        echo "Missing React HTML bundle: ${output_dir}/index.html" >&2
        exit 1
    fi
    if [[ ! -f "${output_dir}/assets/app.js" ]]; then
        echo "Missing React JS bundle: ${output_dir}/assets/app.js" >&2
        exit 1
    fi
    if [[ ! -f "${output_dir}/assets/app.css" ]]; then
        echo "Missing React CSS bundle: ${output_dir}/assets/app.css" >&2
        exit 1
    fi

    echo "${current_hash}" > "${output_dir}/.source-hash"
    echo "Updated embedded UI assets in ${output_dir}"
}

freeze_ui_release_action() {
    local release_dir="${PROJECT_DIR}/web/dist-release"
    local tmp_out="/tmp/camflow-ui-release-build"
    local tmp_work="/tmp/camflow-ui-release-work"

    if ! command -v npm >/dev/null 2>&1; then
        echo "npm is required to freeze UI release assets." >&2
        exit 1
    fi

    build_web_ui "${tmp_out}" "${tmp_work}"

    rm -rf "${release_dir}"
    mkdir -p "${release_dir}"
    cp -R "${tmp_out}/." "${release_dir}/"
    compute_ui_source_hash > "${release_dir}/.source-hash"
    echo "Updated committed UI assets in ${release_dir}"
}

build_runtime_dev() {
    local arch
    local build_dir
    local cache_file
    local generator
    local active_generator
    local configure_args=()
    local opencv_dir
    local opencv_build_dir
    local opencv_install_script

    arch="$(host_arch)"
    build_dir="${PROJECT_DIR}/build-runtime"
    cache_file="${build_dir}/CMakeCache.txt"
    generator="Ninja"
    active_generator=""
    opencv_dir="${OPENCV_DIR:-${PROJECT_DIR}/opencv/${OPENCV_VERSION}/linux-${arch}}"
    opencv_build_dir="${OPENCV_BUILD_DIR:-${PROJECT_DIR}/opencv/${OPENCV_VERSION}/build-linux-${arch}}"
    opencv_install_script="${PROJECT_DIR}/.github/scripts/install-opencv-${OPENCV_VERSION}.sh"

    if [[ ! -x "${opencv_install_script}" ]]; then
        echo "Unsupported OpenCV version ${OPENCV_VERSION}: missing ${opencv_install_script}" >&2
        exit 1
    fi

    CAMFLOW_SKIP_APT=1 "${opencv_install_script}" "${opencv_dir}" "${opencv_build_dir}"

    if [[ -f "${cache_file}" ]]; then
        active_generator="$(sed -n 's/^CMAKE_GENERATOR:INTERNAL=//p' "${cache_file}" | head -n 1)"
    fi

    if [[ -z "${active_generator}" ]]; then
        if command -v ninja >/dev/null 2>&1; then
            configure_args+=("-G" "${generator}")
            echo "Configuring local runtime build with generator: ${generator}"
        else
            echo "Ninja not found; falling back to CMake default generator"
        fi
    else
        echo "Reusing existing local runtime generator: ${active_generator}"
    fi

    configure_args+=(
        -S "${PROJECT_DIR}"
        -B "${build_dir}"
        -DBUILD_RUNTIME=ON
        -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"
        -DOpenCV_DIR="${opencv_dir}/lib/cmake/opencv4"
    )

    if command -v ccache >/dev/null 2>&1; then
        configure_args+=(
            -DCMAKE_C_COMPILER_LAUNCHER=ccache
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        )
        echo "Enabled compiler cache: ccache"
    fi

    cmake "${configure_args[@]}"
    cmake --build "${build_dir}" --parallel
}

build_runtime_arm64() {
    local image_name
    local build_dir
    local rebuild_image
    local opencv_dir
    local opencv_build_dir
    local opencv_install_script
    local arm64_ui_out_dir
    local arm64_ui_work_dir
    local arm64_ccache_dir

    image_name="${IMAGE_NAME:-${DEFAULT_ARM64_IMAGE}}"
    build_dir="${ARM64_BUILD_DIR:-${DEFAULT_ARM64_BUILD_DIR}}"
    rebuild_image="${ARM64_REBUILD_IMAGE:-${DEFAULT_ARM64_REBUILD_IMAGE}}"
    opencv_dir="${OPENCV_DIR:-opencv/${OPENCV_VERSION}/linux-arm64}"
    opencv_build_dir="${OPENCV_BUILD_DIR:-opencv/${OPENCV_VERSION}/build-linux-arm64}"
    opencv_install_script="${PROJECT_DIR}/.github/scripts/install-opencv-${OPENCV_VERSION}.sh"
    arm64_ui_out_dir="${PROJECT_DIR}/${build_dir}/web-dist"
    arm64_ui_work_dir="${PROJECT_DIR}/${build_dir}/web-build"
    arm64_ccache_dir="${PROJECT_DIR}/.ccache-arm64"

    if [[ ! -x "${opencv_install_script}" ]]; then
        echo "Unsupported OpenCV version ${OPENCV_VERSION}: missing ${opencv_install_script}" >&2
        exit 1
    fi

    # Pre-build the web UI on the host (current Node) so the arm64 container,
    # which only has the C++ toolchain, finds up-to-date assets and skips npm.
    echo "Building web UI assets on host for arm64 embed: ${arm64_ui_out_dir}"
    build_web_ui "${arm64_ui_out_dir}" "${arm64_ui_work_dir}"
    mkdir -p "${arm64_ccache_dir}"

    local dockerfile_hash
    local image_dockerfile_hash=""
    dockerfile_hash="$(sha256sum "${PROJECT_DIR}/docker/ubuntu-arm64/Dockerfile" | awk '{print $1}')"
    if docker image inspect "${image_name}" >/dev/null 2>&1; then
        image_dockerfile_hash="$(docker image inspect "${image_name}" --format '{{index .Config.Labels "camflow.dockerfile-hash"}}' 2>/dev/null || true)"
    fi

    if [[ "${rebuild_image}" == "1" || -z "${image_dockerfile_hash}" || "${image_dockerfile_hash}" != "${dockerfile_hash}" ]]; then
        echo "Building ARM64 Docker image: ${image_name}"
        docker build --platform linux/arm64 \
            --label "camflow.dockerfile-hash=${dockerfile_hash}" \
            -t "${image_name}" \
            "${PROJECT_DIR}/docker/ubuntu-arm64"
    else
        echo "Reusing ARM64 Docker image: ${image_name}"
    fi

    docker run --rm --platform linux/arm64 \
        --user "$(id -u):$(id -g)" \
        -e HOME=/tmp \
        -e CCACHE_DIR=/ccache \
        -v "${PROJECT_DIR}:/workspace" \
        -v "${arm64_ccache_dir}:/ccache" \
        -w /workspace \
        "${image_name}" \
        bash -lc "git config --global --add safe.directory /workspace && ccache --set-config=max_size=5G && CAMFLOW_SKIP_APT=1 ./.github/scripts/install-opencv-${OPENCV_VERSION}.sh /workspace/${opencv_dir} /workspace/${opencv_build_dir} && ccache_flags='-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache' && echo 'Enabled persistent ccache: \${CCACHE_DIR} (size limit: 5G)' && cmake -B ${build_dir} -G Ninja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_RUNTIME=ON -DOpenCV_DIR=/workspace/${opencv_dir}/lib/cmake/opencv4 \${ccache_flags} && cmake --build ${build_dir} --parallel"
}

deploy_runtime_arm64() {
    local target_spec="${USER}@${TARGET}"
    local ssh_opts=(
        -o BatchMode=yes
        -o StrictHostKeyChecking=accept-new
        -o ConnectTimeout=8
        -o ConnectionAttempts=1
        -o ServerAliveInterval=5
        -o ServerAliveCountMax=2
        -n
    )
    local scp_opts=(
        -o BatchMode=yes
        -o StrictHostKeyChecking=accept-new
        -o ConnectTimeout=8
        -o ConnectionAttempts=1
        -o ServerAliveInterval=5
        -o ServerAliveCountMax=2
    )
    local build_dir="${ARM64_BUILD_DIR:-${DEFAULT_ARM64_BUILD_DIR}}"
    local binary_path="${PROJECT_DIR}/${build_dir}/camflow"
    local legacy_binary_path="${PROJECT_DIR}/${build_dir}/src/runtime/camflow"
    local resolved_binary_path="${binary_path}"

    if [[ ! -f "${resolved_binary_path}" && -f "${legacy_binary_path}" ]]; then
        resolved_binary_path="${legacy_binary_path}"
    fi

    if [[ ! -f "${resolved_binary_path}" ]]; then
        echo "Binary not found: ${resolved_binary_path}" >&2
        echo "Build first: ./scripts/tasks.sh build arm64 runtime" >&2
        exit 1
    fi

    echo "Creating target directory ${TARGET_DIR} on ${target_spec}"
    ssh "${ssh_opts[@]}" "${target_spec}" "mkdir -p '${TARGET_DIR}'"

    echo "Checking running camflow on ${target_spec}"
    if ssh "${ssh_opts[@]}" "${target_spec}" "command -v pgrep >/dev/null && pgrep -x camflow >/dev/null"; then
        echo "Stopping running camflow on ${target_spec}"
        ssh "${ssh_opts[@]}" "${target_spec}" "if command -v pkill >/dev/null 2>&1; then pkill -x camflow || true; elif command -v pgrep >/dev/null 2>&1; then for pid in \$(pgrep -x camflow || true); do kill \"\$pid\" || true; done; fi"

        local stopped=false
        local i
        for ((i = 0; i < 10; ++i)); do
            if ! ssh "${ssh_opts[@]}" "${target_spec}" "command -v pgrep >/dev/null && pgrep -x camflow >/dev/null"; then
                stopped=true
                break
            fi
            sleep 0.1
        done

        if [[ "${stopped}" != "true" ]]; then
            echo "Failed to stop running camflow on ${target_spec}" >&2
            exit 1
        fi
    else
        echo "No running camflow process found on ${target_spec}"
    fi

    local remote_tmp_path="/tmp/camflow.deploy.$$"

    echo "Copying binary to ${target_spec}:${remote_tmp_path}"
    scp "${scp_opts[@]}" "${resolved_binary_path}" "${target_spec}:${remote_tmp_path}"

    echo "Installing binary to ${target_spec}:${TARGET_DIR}/camflow"
    ssh "${ssh_opts[@]}" "${target_spec}" "chmod +x '${remote_tmp_path}' && mv -f '${remote_tmp_path}' '${TARGET_DIR}/camflow'"

    echo "Deploy finished: ${target_spec}:${TARGET_DIR}/camflow"
}

run_runtime_dev() {
    local tail_log="${1:-${TAIL_LOG}}"
    local binary_path="${PROJECT_DIR}/build-runtime/camflow"
    local runtime_args=(--verbose "${VERBOSE_LEVEL}" --port "${PORT}")

    if [[ ! -f "${binary_path}" ]]; then
        echo "Binary not found: ${binary_path}" >&2
        echo "Build first: ./scripts/tasks.sh build dev runtime" >&2
        exit 1
    fi

    pkill -x camflow || true
    chmod +x "${binary_path}"
    if [[ -n "${LOCAL_DEVICE}" ]]; then
        runtime_args+=(--device "${LOCAL_DEVICE}")
    fi
    if [[ -n "${LOCAL_SUBDEVICES}" ]]; then
        runtime_args+=(--subdevices "${LOCAL_SUBDEVICES}")
    fi
    nohup "${binary_path}" "${runtime_args[@]}" >"${LOG_PATH}" 2>&1 </dev/null &

    echo "Local camflow started: http://127.0.0.1:${PORT}"
    echo "Local log: ${LOG_PATH}"

    if [[ "${tail_log}" == "1" ]]; then
        tail -n +1 -f "${LOG_PATH}"
    fi
}

run_runtime_arm64() {
    local tail_log="${1:-${TAIL_LOG}}"
    local stop_existing="${2:-1}"
    local target_spec="${USER}@${TARGET}"
    local remote_log="/tmp/camflow-ui.log"
    local runtime_args="--verbose '${VERBOSE_LEVEL}' --port '${PORT}'"
    local ssh_opts=(
        -o BatchMode=yes
        -o ConnectTimeout=8
        -o ConnectionAttempts=1
        -o ServerAliveInterval=5
        -o ServerAliveCountMax=2
        -n
    )

    if [[ "${stop_existing}" == "1" ]]; then
        echo "Stopping running camflow on ${target_spec} (if active)"
        ssh "${ssh_opts[@]}" "${target_spec}" "if command -v pkill >/dev/null 2>&1; then pkill -x camflow || true; elif command -v pgrep >/dev/null 2>&1; then for pid in \$(pgrep -x camflow || true); do kill \"\$pid\" || true; done; fi"
    else
        echo "Skipping runtime stop: deploy already stopped camflow on ${target_spec}"
    fi

    if [[ -n "${REMOTE_DEVICE}" ]]; then
        runtime_args+=" --device '${REMOTE_DEVICE}'"
    fi
    if [[ -n "${REMOTE_SUBDEVICES}" ]]; then
        runtime_args+=" --subdevices '${REMOTE_SUBDEVICES}'"
    fi

    echo "Starting camflow UI mode on ${target_spec}:${PORT}"
    ssh "${ssh_opts[@]}" "${target_spec}" "chmod +x '${TARGET_DIR}/camflow' && : > '${remote_log}' && if command -v setsid >/dev/null 2>&1; then setsid '${TARGET_DIR}/camflow' ${runtime_args} >'${remote_log}' 2>&1 < /dev/null & else nohup '${TARGET_DIR}/camflow' ${runtime_args} >'${remote_log}' 2>&1 </dev/null & fi"

    echo "UI started: http://${TARGET}:${PORT}"
    if [[ "${tail_log}" == "1" ]]; then
        echo "Streaming remote camflow log from ${target_spec} (Ctrl-C detaches, camflow keeps running)"
        ssh "${ssh_opts[@]}" "${target_spec}" "tail -n +1 -f '${remote_log}'"
    else
        echo "Remote log tail disabled (TAIL_LOG=${tail_log})"
        echo "Inspect log manually: ssh ${target_spec} tail -f '${remote_log}'"
    fi
}

run_ui_dev() {
    local ui_dir="${PROJECT_DIR}/web"
    local api_target="http://127.0.0.1:${UI_API_PORT}"
    local ws_target="ws://127.0.0.1:${UI_API_PORT}"

    install_ui_dependencies "${ui_dir}"

    echo "UI dev server (HMR): http://127.0.0.1:${UI_DEV_PORT}"
    echo "Proxy target: ${api_target}"
    echo "Direct WS target: ${ws_target}"

    (
        cd "${ui_dir}"
        CAMFLOW_WEB_DEV_PORT="${UI_DEV_PORT}" \
        CAMFLOW_WEB_API_TARGET="${api_target}" \
        VITE_CAMFLOW_WS_TARGET="${ws_target}" \
        npm run dev -- --host 0.0.0.0 --strictPort
    )
}

start_ui_dev_background() {
    local ui_dir="${PROJECT_DIR}/web"
    local api_target="http://127.0.0.1:${UI_API_PORT}"
    local ws_target="ws://127.0.0.1:${UI_API_PORT}"
    local ui_log_path="/tmp/camflow-ui-dev.log"

    install_ui_dependencies "${ui_dir}"

    nohup bash -lc "cd '${ui_dir}' && CAMFLOW_WEB_DEV_PORT='${UI_DEV_PORT}' CAMFLOW_WEB_API_TARGET='${api_target}' VITE_CAMFLOW_WS_TARGET='${ws_target}' npm run dev -- --host 0.0.0.0 --strictPort" >"${ui_log_path}" 2>&1 </dev/null &
    echo "UI dev server started in background: http://127.0.0.1:${UI_DEV_PORT}"
    echo "UI dev log: ${ui_log_path}"
}

install_host_dependencies() {
    local apt_prefix=""

    if [[ "${OSTYPE}" != linux* ]]; then
        echo "Unsupported operating system: ${OSTYPE}" >&2
        exit 1
    fi

    if command -v sudo >/dev/null 2>&1; then
        apt_prefix="sudo"
    fi

    ${apt_prefix} apt-get update
    ${apt_prefix} apt-get install -y \
        build-essential \
        cmake \
        ninja-build \
        git \
        pkg-config \
        curl \
        ca-certificates \
        nodejs \
        libeigen3-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libwebp-dev \
        clang-format-15 \
        python3 \
        python3-numpy \
        doxygen \
        graphviz

    if ! command -v node >/dev/null 2>&1; then
        echo "node is missing after dependency install" >&2
        exit 1
    fi

    if ! command -v npm >/dev/null 2>&1; then
        echo "npm is missing after dependency install." >&2
        echo "Install npm from your Node.js distribution (for example NodeSource nodejs includes npm)." >&2
        exit 1
    fi
}

install_project_opencv() {
    local arch
    local install_script

    arch="$(host_arch)"
    install_script="${PROJECT_DIR}/.github/scripts/install-opencv-${OPENCV_VERSION}.sh"

    if [[ ! -x "${install_script}" ]]; then
        echo "OpenCV installer not found for version ${OPENCV_VERSION}: ${install_script}" >&2
        exit 1
    fi

    "${install_script}" \
        "${PROJECT_DIR}/opencv/${OPENCV_VERSION}/linux-${arch}" \
        "${PROJECT_DIR}/opencv/${OPENCV_VERSION}/build-linux-${arch}"
}

install_dependencies_action() {
    install_host_dependencies
    install_project_opencv
    echo "Dependencies installed successfully"
}

format_sources_action() {
    local clang_format_bin="${CLANG_FORMAT_BIN}"

    find "${PROJECT_DIR}/src" -type f \
        \( -name '*.cpp' -o -name '*.hpp' -o -name '*.c' -o -name '*.h' -o -name '*.cc' \) \
        -print0 | xargs -0 "${clang_format_bin}" -i
}

install_doc_dependencies_action() {
    if [[ "${OSTYPE}" == "linux-gnu"* ]]; then
        if command -v sudo >/dev/null 2>&1; then
            sudo apt update >/dev/null 2>&1 || true
            sudo apt install -y doxygen graphviz curl >/dev/null
        else
            apt-get update >/dev/null 2>&1 || true
            apt-get install -y doxygen graphviz curl >/dev/null
        fi
    elif [[ "${OSTYPE}" == "darwin"* ]]; then
        if ! command -v brew >/dev/null; then
            echo "Error: Homebrew is required on macOS." >&2
            exit 1
        fi
        brew install doxygen graphviz curl >/dev/null
    else
        echo "Unsupported operating system: ${OSTYPE}" >&2
        echo "Install manually: doxygen graphviz curl" >&2
        exit 1
    fi
}

download_doxygen_theme() {
    local base_url="https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main"
    local theme_dir="${PROJECT_DIR}/docs/doxygen-awesome"

    mkdir -p "${theme_dir}"
    curl -fsSL "${base_url}/doxygen-awesome.css" -o "${theme_dir}/doxygen-awesome.css"
    curl -fsSL "${base_url}/doxygen-awesome-sidebar-only.css" -o "${theme_dir}/doxygen-awesome-sidebar-only.css"
    curl -fsSL "${base_url}/doxygen-awesome-sidebar-only-darkmode-toggle.css" -o "${theme_dir}/doxygen-awesome-sidebar-only-darkmode-toggle.css"
}

generate_docs_action() {
    local output_dir="${DOCS_OUTPUT_DIR}"
    local theme_dir="${PROJECT_DIR}/docs/doxygen-awesome"
    local config_file="${PROJECT_DIR}/Doxyfile.generated"
    local html_count

    if [[ ${DOCS_INSTALL_DEPS} -eq 1 ]]; then
        install_doc_dependencies_action
    fi

    if ! command -v doxygen >/dev/null; then
        echo "Error: doxygen is not installed." >&2
        echo "Run: ./scripts/tasks.sh docs --install-deps" >&2
        exit 1
    fi
    if ! command -v dot >/dev/null; then
        echo "Error: graphviz (dot) is not installed." >&2
        echo "Run: ./scripts/tasks.sh docs --install-deps" >&2
        exit 1
    fi
    if ! command -v curl >/dev/null; then
        echo "Error: curl is required to download doxygen-awesome theme files." >&2
        exit 1
    fi

    if [[ ${DOCS_CLEAN_FIRST} -eq 1 ]]; then
        rm -rf "${output_dir}"
    fi

    mkdir -p "${output_dir}"
    download_doxygen_theme

    cat > "${config_file}" <<EOF
PROJECT_NAME           = "camflow runtime"
PROJECT_NUMBER         = "0.5.2"
PROJECT_BRIEF          = "Modular real-time vision processing pipeline"
OUTPUT_DIRECTORY       = "${output_dir}"
CREATE_SUBDIRS         = NO
ALLOW_UNICODE_NAMES    = NO
OUTPUT_LANGUAGE        = English

INPUT                  = \
    "${PROJECT_DIR}/src"
FILE_PATTERNS          = *.h *.hpp
RECURSIVE              = YES
EXCLUDE_PATTERNS       = */tests/* */opencv-*/* */build-*/*

EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
EXTRACT_LOCAL_CLASSES  = YES
HIDE_UNDOC_MEMBERS     = NO
HIDE_UNDOC_CLASSES     = NO

QUIET                  = NO
WARNINGS               = YES
WARN_IF_UNDOCUMENTED   = NO

GENERATE_HTML          = YES
HTML_OUTPUT            = .
HTML_FILE_EXTENSION    = .html
HTML_DYNAMIC_MENUS     = YES
DISABLE_INDEX          = NO
GENERATE_TREEVIEW      = NO

HTML_EXTRA_STYLESHEET  = \
  "${theme_dir}/doxygen-awesome.css" \
  "${theme_dir}/doxygen-awesome-sidebar-only.css" \
  "${theme_dir}/doxygen-awesome-sidebar-only-darkmode-toggle.css"

USE_MDFILE_AS_MAINPAGE = "${PROJECT_DIR}/README.md"
MARKDOWN_SUPPORT       = YES
AUTOLINK_SUPPORT       = YES

HAVE_DOT               = YES
CLASS_DIAGRAMS         = YES
DOT_IMAGE_FORMAT       = svg
INTERACTIVE_SVG        = YES
DOT_GRAPH_MAX_NODES    = 100

GENERATE_XML           = NO
GENERATE_LATEX         = NO
GENERATE_MAN           = NO
GENERATE_RTF           = NO
EOF

    doxygen "${config_file}"
    rm -f "${config_file}"

    html_count=$(find "${output_dir}" -name "*.html" -type f | wc -l | tr -d ' ')
    echo "Documentation generated successfully"
    echo "Output: ${output_dir}"
    echo "Files: ${html_count} HTML files"
}

if has_help_flag "$@"; then
    print_help
    exit 0
fi

commands=()
platforms=()
products=()

CLI_TARGET=
CLI_TARGET_DIR=
CLI_PORT=
CLI_TAIL_LOG=
CLI_LOG_PATH=
CLI_USER=
CLI_OPENCV_VERSION=
CLI_UI_OUT_DIR=
CLI_UI_WORK_DIR=
CLI_UI_DEV_PORT=
CLI_UI_API_PORT=
CLI_ARM64_REBUILD_IMAGE=
CLI_CLANG_FORMAT_BIN=
CLI_DOCS_OUTPUT_DIR=
DOCS_CLEAN_FIRST=0
DOCS_INSTALL_DEPS=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        build|deploy|run|deps|format|docs|ui-release)
            commands+=("$1")
            shift
            ;;
        dev|arm64)
            platforms+=("$1")
            shift
            ;;
        runtime|ui)
            products+=("$1")
            shift
            ;;
        --ip)
            CLI_TARGET="${2:?--ip requires a host or IP}"
            shift 2
            ;;
        --dir)
            CLI_TARGET_DIR="${2:?--dir requires a path}"
            shift 2
            ;;
        --port)
            CLI_PORT="${2:?--port requires a port number}"
            shift 2
            ;;
        --tail-log)
            CLI_TAIL_LOG="${2:?--tail-log requires 0 or 1}"
            shift 2
            ;;
        --log-path)
            CLI_LOG_PATH="${2:?--log-path requires a file path}"
            shift 2
            ;;
        --user)
            CLI_USER="${2:?--user requires a user name}"
            shift 2
            ;;
        --opencv)
            CLI_OPENCV_VERSION="${2:?--opencv requires a version}"
            shift 2
            ;;
        --rebuild-image)
            CLI_ARM64_REBUILD_IMAGE="${2:?--rebuild-image requires 0 or 1}"
            shift 2
            ;;
        --ui-out)
            CLI_UI_OUT_DIR="${2:?--ui-out requires a directory path}"
            shift 2
            ;;
        --ui-work)
            CLI_UI_WORK_DIR="${2:?--ui-work requires a directory path}"
            shift 2
            ;;
        --ui-port)
            CLI_UI_DEV_PORT="${2:?--ui-port requires a port number}"
            shift 2
            ;;
        --api-port)
            CLI_UI_API_PORT="${2:?--api-port requires a port number}"
            shift 2
            ;;
        --clang-format)
            CLI_CLANG_FORMAT_BIN="${2:?--clang-format requires an executable name or path}"
            shift 2
            ;;
        --clean)
            DOCS_CLEAN_FIRST=1
            shift
            ;;
        --output)
            CLI_DOCS_OUTPUT_DIR="${2:?--output requires a directory path}"
            shift 2
            ;;
        --install-deps)
            DOCS_INSTALL_DEPS=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Unknown argument: $1" >&2
            print_help
            exit 1
            ;;
    esac
done

if [[ ${#commands[@]} -eq 0 ]]; then
    echo "At least one command is required." >&2
    print_help
    exit 1
fi

if has_command build || has_command deploy || has_command run || has_command deps; then
    if [[ ${#platforms[@]} -eq 0 ]]; then
        platforms=(dev arm64)
    fi
    if [[ ${#products[@]} -eq 0 ]]; then
        products=(runtime ui)
    fi

    ensure_make_cfg
    load_make_cfg
elif [[ -f "${MAKE_CFG_PATH}" ]]; then
    load_make_cfg
fi

BUILD_TYPE=${BUILD_TYPE:-${DEFAULT_BUILD_TYPE}}
TARGET=${TARGET:-${DEFAULT_TARGET}}
TARGET_DIR=${TARGET_DIR:-${DEFAULT_TARGET_DIR}}
PORT=${PORT:-${DEFAULT_PORT}}
USER=${USER:-${DEFAULT_USER}}
OPENCV_VERSION=${OPENCV_VERSION:-${DEFAULT_OPENCV_VERSION}}
LOCAL_DEVICE=${LOCAL_DEVICE-${DEFAULT_LOCAL_DEVICE}}
LOCAL_SUBDEVICES=${LOCAL_SUBDEVICES-${DEFAULT_LOCAL_SUBDEVICES}}
REMOTE_DEVICE=${REMOTE_DEVICE-${DEFAULT_REMOTE_DEVICE}}
REMOTE_SUBDEVICES=${REMOTE_SUBDEVICES-${DEFAULT_REMOTE_SUBDEVICES}}
TAIL_LOG=${TAIL_LOG:-${DEFAULT_TAIL_LOG}}
VERBOSE_LEVEL=${VERBOSE_LEVEL:-${DEFAULT_VERBOSE_LEVEL}}
LOG_PATH=${LOG_PATH:-${DEFAULT_LOG_PATH}}
UI_OUT_DIR=${UI_OUT_DIR:-${DEFAULT_UI_OUT_DIR}}
UI_WORK_DIR=${UI_WORK_DIR:-${DEFAULT_UI_WORK_DIR}}
UI_DEV_PORT=${UI_DEV_PORT:-${DEFAULT_UI_DEV_PORT}}
UI_API_PORT=${UI_API_PORT:-${DEFAULT_UI_API_PORT}}
ARM64_REBUILD_IMAGE=${ARM64_REBUILD_IMAGE:-${DEFAULT_ARM64_REBUILD_IMAGE}}
CLANG_FORMAT_BIN=${CLANG_FORMAT_BIN:-clang-format-15}
DOCS_OUTPUT_DIR=${DOCS_OUTPUT_DIR:-${PROJECT_DIR}/docs/api}

if [[ -n "${CLI_TARGET}" ]]; then TARGET="${CLI_TARGET}"; fi
if [[ -n "${CLI_TARGET_DIR}" ]]; then TARGET_DIR="${CLI_TARGET_DIR}"; fi
if [[ -n "${CLI_PORT}" ]]; then PORT="${CLI_PORT}"; fi
if [[ -n "${CLI_TAIL_LOG}" ]]; then TAIL_LOG="${CLI_TAIL_LOG}"; fi
if [[ -n "${CLI_LOG_PATH}" ]]; then LOG_PATH="${CLI_LOG_PATH}"; fi
if [[ -n "${CLI_USER}" ]]; then USER="${CLI_USER}"; fi
if [[ -n "${CLI_OPENCV_VERSION}" ]]; then OPENCV_VERSION="${CLI_OPENCV_VERSION}"; fi
if [[ -n "${CLI_UI_OUT_DIR}" ]]; then UI_OUT_DIR="${CLI_UI_OUT_DIR}"; fi
if [[ -n "${CLI_UI_WORK_DIR}" ]]; then UI_WORK_DIR="${CLI_UI_WORK_DIR}"; fi
if [[ -n "${CLI_UI_DEV_PORT}" ]]; then UI_DEV_PORT="${CLI_UI_DEV_PORT}"; fi
if [[ -n "${CLI_UI_API_PORT}" ]]; then UI_API_PORT="${CLI_UI_API_PORT}"; fi
if [[ -n "${CLI_ARM64_REBUILD_IMAGE}" ]]; then ARM64_REBUILD_IMAGE="${CLI_ARM64_REBUILD_IMAGE}"; fi
if [[ -n "${CLI_CLANG_FORMAT_BIN}" ]]; then CLANG_FORMAT_BIN="${CLI_CLANG_FORMAT_BIN}"; fi
if [[ -n "${CLI_DOCS_OUTPUT_DIR}" ]]; then DOCS_OUTPUT_DIR="${CLI_DOCS_OUTPUT_DIR}"; fi

if [[ "${TAIL_LOG}" != "0" && "${TAIL_LOG}" != "1" ]]; then
    echo "Invalid --tail-log value: ${TAIL_LOG} (expected 0 or 1)" >&2
    exit 1
fi

if [[ "${ARM64_REBUILD_IMAGE}" != "0" && "${ARM64_REBUILD_IMAGE}" != "1" ]]; then
    echo "Invalid --rebuild-image value: ${ARM64_REBUILD_IMAGE} (expected 0 or 1)" >&2
    exit 1
fi

want_dev=0
want_arm64=0
want_runtime=0
want_ui=0

if [[ " ${platforms[*]} " == *" dev "* ]]; then
    want_dev=1
fi
if [[ " ${platforms[*]} " == *" arm64 "* ]]; then
    want_arm64=1
fi
if [[ " ${products[*]} " == *" runtime "* ]]; then
    want_runtime=1
fi
if [[ " ${products[*]} " == *" ui "* ]]; then
    want_ui=1
fi

did_deploy_arm64=0

for command in "${commands[@]}"; do
    case "${command}" in
        ui-release)
            freeze_ui_release_action
            ;;
        build)
            if [[ ${want_ui} -eq 1 ]]; then
                build_web_ui
            fi
            if [[ ${want_runtime} -eq 1 ]]; then
                if [[ ${want_dev} -eq 1 ]]; then
                    build_runtime_dev
                fi
                if [[ ${want_arm64} -eq 1 ]]; then
                    build_runtime_arm64
                fi
            fi
            ;;
        deploy)
            if [[ ${want_runtime} -eq 1 && ${want_arm64} -eq 1 ]]; then
                deploy_runtime_arm64
                did_deploy_arm64=1
            else
                echo "Skipping deploy: only runtime/arm64 can be deployed." >&2
            fi
            ;;
        run)
            if [[ ${want_runtime} -eq 0 && ${want_ui} -eq 0 ]]; then
                echo "Skipping run: no runnable product selected (runtime/ui)." >&2
                continue
            fi

            if [[ ${want_ui} -eq 1 && ${want_dev} -eq 0 ]]; then
                echo "Skipping UI run: UI dev server is only supported on dev platform." >&2
            fi

            if [[ ${want_ui} -eq 1 && ${want_dev} -eq 1 && ${want_runtime} -eq 0 ]]; then
                run_ui_dev
                continue
            fi

            run_tail_log=${TAIL_LOG}
            if [[ ${want_dev} -eq 1 && ${want_arm64} -eq 1 ]]; then
                run_tail_log=0
            fi

            if [[ ${want_runtime} -eq 1 && ${want_dev} -eq 1 && ${want_ui} -eq 1 ]]; then
                start_ui_dev_background
            fi

            if [[ ${want_dev} -eq 1 ]]; then
                run_runtime_dev "${run_tail_log}"
            fi
            if [[ ${want_arm64} -eq 1 ]]; then
                if [[ ${did_deploy_arm64} -eq 0 ]]; then
                    deploy_runtime_arm64
                fi
                run_runtime_arm64 "${run_tail_log}" "$((1 - did_deploy_arm64))"
            fi
            ;;
        deps)
            install_dependencies_action
            ;;
        format)
            format_sources_action
            ;;
        docs)
            generate_docs_action
            ;;
        *)
            echo "Unknown command: ${command}" >&2
            exit 1
            ;;
    esac
done
