name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  runtime:
    uses: ./.github/workflows/build-release-package.yml
    with:
      version: ${{ github.ref_name }}

  release:
    needs: [runtime]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
